"""AI-generated model library: identity cards, defaults, candidates, and per-project pinning.

Models are fictional people generated by the host image tool. Real people, lookalikes,
and photos of real people are refused. Projects pin a copy of the model image and its
hash, so later library changes never alter an existing try-on.
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
from pathlib import Path

from .config import ensure_external
from .errors import ValidationError
from .presentation import (
    PRESENTATION_FOLDERS,
    check_image,
    file_index,
    kept_ids,
    library_root,
    next_round,
    presentation_error,
    record_decision,
    register_entries,
    sha256,
)
from .store import _utc_now, load_state, write_atomic

IDENTITY_KEYS = (
    "id", "display_name", "gender_presentation", "age_range", "build", "height_impression", "skin_tone",
    "hair", "face_description", "neutral_outfit", "lighting", "camera", "background",
)
RANGE_KEYS = ("gender_presentation", "age_range", "build", "skin_tone", "hair")
MODEL_ID = re.compile(r"^m-[a-z0-9-]{1,40}$")
REAL_PERSON = re.compile(
    r"\b(?:celebrit\w*|look[- ]?alike|looks?\s+like|resembl\w*|influencer|famous|actor|actress|singer|athlete"
    r"|in\s+the\s+style\s+of|real\s+person|photo\s+of\s+(?:me|my|a\s+friend))\b",
    re.IGNORECASE,
)
FOLDER = PRESENTATION_FOLDERS["synthetic_model"]
LABELS = ("A", "B", "C", "W")
NO_REAL_PERSON = "Fictional AI-generated fashion model, not based on or resembling any real person."


def refuse_real_person(*texts: str) -> None:
    for text in texts:
        if isinstance(text, str) and REAL_PERSON.search(text):
            raise presentation_error("real_person_model_refused",
                                     "Models must be fictional; real people and lookalikes are refused.",
                                     "Describe the model by build, age range, skin tone, and hair only.")


def validate_identity(card: dict) -> dict:
    if not isinstance(card, dict):
        raise ValidationError("Identity card must be an object.", field="identity", recovery="Send a JSON object.")
    missing = [key for key in IDENTITY_KEYS if not isinstance(card.get(key), str) or not card[key].strip()]
    if missing or not MODEL_ID.match(card.get("id", "")):
        raise ValidationError(f"Identity card is incomplete: {', '.join(missing) or 'id'}.", field="identity",
                              recovery="Fill every identity field; ids look like `m-aria`.")
    refuse_real_person(*(card[key] for key in IDENTITY_KEYS))
    return {**{key: card[key].strip() for key in IDENTITY_KEYS}, "ai_generated_person": True,
            "renderer": str(card.get("renderer") or "unrendered"), "prompt": str(card.get("prompt") or NO_REAL_PERSON)}


def _library(project: Path) -> Path:
    root = library_root(project)
    ensure_external(root.parent, Path(__file__).resolve().parents[2])
    return root


def library_models(project: Path) -> dict[str, dict]:
    root = library_root(project)
    models = {}
    if root.is_dir():
        for folder in sorted(root.iterdir()):
            card = folder / "identity.json"
            if card.is_file():
                identity = json.loads(card.read_text("utf-8"))
                front = folder / "front.png"
                identity["front_image"] = str(front) if front.is_file() else None
                models[identity["id"]] = identity
    return models


def install_defaults(project: Path, bundle_dir: Path) -> dict:
    root = _library(project)
    installed, missing = [], []
    for folder in sorted((Path(bundle_dir) / "assets/models").iterdir()):
        if not (folder / "identity.json").is_file():
            continue  # ignore stray files such as .DS_Store
        card = validate_identity(json.loads((folder / "identity.json").read_text("utf-8")))
        target = root / card["id"]
        if not (target / "identity.json").exists():
            write_atomic(target / "identity.json", (json.dumps(card, indent=2, sort_keys=True) + "\n").encode("utf-8"))
            if (folder / "front.png").is_file():
                shutil.copyfile(folder / "front.png", target / "front.png")
            installed.append(card["id"])
        if not (target / "front.png").is_file():
            missing.append(card["id"])
    return {"installed": installed, "missing_images": missing, "library": str(root)}


def _model_prompt(card: dict) -> str:
    return (f"{NO_REAL_PERSON} {card['gender_presentation']}, age {card['age_range']}, {card['build']}, "
            f"{card['height_impression']}, {card['skin_tone']} skin, {card['hair']}, {card['face_description']}. "
            f"Wearing {card['neutral_outfit']}. {card['lighting']}. {card['camera']}. {card['background']}. "
            "Front view, standing straight, arms relaxed at sides.")


def _candidate_id(state: dict, round_number: int, label: str) -> str:
    """Project-scoped candidate id, so kept candidates never collide in the shared library.

    The namespace hashes the project's slug and creation time: stable for the project's
    life, different across projects, and free of any filesystem path.
    """
    seed = f"{state['project_slug']}\n{state['created_at']}".encode("utf-8")
    namespace = hashlib.sha256(seed).hexdigest()[:8]
    return f"m-{namespace}-r{round_number:02d}-{label.lower()}"


def plan_models(project: Path, payload: dict) -> dict:
    spec = payload.get("range")
    if not isinstance(spec, dict) or any(not isinstance(spec.get(key), str) or not spec[key].strip()
                                         for key in RANGE_KEYS):
        raise ValidationError(f"Describe the model range with: {', '.join(RANGE_KEYS)}.", field="range",
                              recovery="Ask the user for gender presentation, age range, build, skin tone, and hair.")
    refuse_real_person(*spec.values())
    state = load_state(project)
    round_number = next_round(state, "synthetic_model", "kind", "candidate")
    jobs, identities = [], {}
    for label in LABELS:
        identity = validate_identity({
            "id": _candidate_id(state, round_number, label), "display_name": f"Candidate {label}",
            "gender_presentation": spec["gender_presentation"], "age_range": spec["age_range"],
            "build": spec["build"], "height_impression": "average", "skin_tone": spec["skin_tone"],
            "hair": spec["hair"], "face_description": f"distinct face {label}, neutral expression",
            "neutral_outfit": "plain white fitted crew tee and straight black trousers",
            "lighting": "soft even studio light", "camera": "full-length, eye level, centred",
            "background": "plain warm-grey studio backdrop #E9E6DF",
        })
        identities[label] = identity
        jobs.append({"label": label, "prompt": _model_prompt(identity) + (
            " Vary one visible trait from the other candidates." if label == "W" else ""),
            "destination": f"{FOLDER}candidates/r{round_number:02d}/model-{label}.png", "aspect": "3:4"})
    return {"round": round_number, "jobs": jobs, "identities": identities}


def plan_reference(project: Path, payload: dict) -> dict:
    model = library_models(project).get(payload.get("model_id"))
    if model is None:
        raise presentation_error("model_not_kept", "That model is not in the library.",
                                 "Install defaults or keep a candidate first.", field="model_id")
    return {"jobs": [{"model_id": model["id"], "prompt": _model_prompt(model),
                      "destination": f"{FOLDER}references/{model['id']}-front.png", "aspect": "3:4"}]}


def _round(value) -> int:
    """Planned round numbers are positive integers; anything else is a caller error."""
    if isinstance(value, bool) or not isinstance(value, int) or value < 1:
        raise ValidationError("Send the planned round number as an integer of at least 1.", field="round",
                              recovery="Use `round` from the `create_models` plan.")
    return value


def register_models(project: Path, payload: dict, now: str | None = None) -> list[dict]:
    kind = payload.get("kind")
    timestamp = now or _utc_now()
    results = payload.get("results")
    if not isinstance(results, list) or not results:
        raise ValidationError("Send the rendered model images.", field="results", recovery="Include path and prompt.")
    entries = []
    if kind == "candidates":
        identities = payload.get("identities") or {}
        round_number = _round(payload.get("round"))
        state = load_state(project)
        for result in results:
            label = result.get("label")
            expected = f"{FOLDER}candidates/r{round_number:02d}/model-{label}.png"
            if label not in LABELS or result.get("path") != expected:
                raise ValidationError("Register candidates at their planned destinations.", field="path",
                                      recovery=f"Save candidate {label} as {expected}.")
            absolute, relative = check_image(project, result["path"], FOLDER)
            identity = validate_identity(identities.get(label) or {})
            if identity["id"] != _candidate_id(state, round_number, label):
                raise ValidationError("Candidate identity does not match this project's planned id.",
                                      field="identities",
                                      recovery="Register the identities returned by this project's plan unchanged.")
            entries.append({"id": identity["id"], "origin": "synthetic_model", "path": relative,
                            "sha256": sha256(absolute), "parents": [], "registered_at": timestamp,
                            "production_eligible": False, "kind": "candidate", "round": round_number,
                            "ai_generated_person": True, "identity": identity,
                            "renderer": str(result.get("renderer") or "unknown")})
        register_entries(project, entries, timestamp)
        return entries
    if kind == "reference":
        library = library_models(project)
        for result in results:
            model = library.get(result.get("model_id"))
            expected = f"{FOLDER}references/{result.get('model_id')}-front.png"
            if model is None or result.get("path") != expected:
                raise ValidationError("Register the reference at its planned destination.", field="path",
                                      recovery=f"Save it as {expected}.")
            absolute, _ = check_image(project, result["path"], FOLDER)
            shutil.copyfile(absolute, library_root(project) / model["id"] / "front.png")
            entries.append({"model_id": model["id"], "library_image": str(library_root(project) / model["id"])})
        return entries
    raise ValidationError("Kind must be `candidates` or `reference`.", field="kind",
                          recovery="Use the kind returned by the plan.")


def keep_models(project: Path, payload: dict, now: str | None = None) -> dict:
    state = load_state(project)
    files = file_index(state)
    ids = payload.get("ids")
    if not isinstance(ids, list) or not ids or any(files.get(i, {}).get("kind") != "candidate" for i in ids):
        raise ValidationError("Keep registered model candidates only.", field="ids",
                              recovery="Send ids returned by `create_models` register.")
    record_decision(project, "model", ids, "keep", payload.get("user_quote"), now)
    root = _library(project)
    for model_id in ids:
        entry = files[model_id]
        target = root / model_id
        write_atomic(target / "identity.json",
                     (json.dumps({**entry["identity"], "renderer": entry["renderer"]}, indent=2, sort_keys=True)
                      + "\n").encode("utf-8"))
        shutil.copyfile(project / entry["path"], target / "front.png")
    return {"models": ids, "library": str(root)}


def pin_model(project: Path, model_id: str, now: str | None = None) -> dict:
    state = load_state(project)
    for entry in state.get("files", []):
        if entry.get("origin") == "synthetic_model" and entry.get("library_model_id") == model_id:
            return entry
    model = library_models(project).get(model_id)
    kept_candidate = model_id in kept_ids(state, "model")
    if model is None or not model.get("front_image"):
        raise presentation_error("model_not_kept",
                                 "That model is not in the library or has no reference image yet.",
                                 "Keep a candidate, or run `create_models` mode `plan_reference` for a default.",
                                 field="model_id")
    relative = f"{FOLDER}pinned/{model_id}-front.png"
    target = project / relative
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(model["front_image"], target)
    timestamp = now or _utc_now()
    entry = {"id": f"pin-{model_id}", "origin": "synthetic_model", "path": relative, "sha256": sha256(target),
             "parents": [], "registered_at": timestamp, "production_eligible": False, "kind": "pinned",
             "library_model_id": model_id, "ai_generated_person": True, "kept_candidate": kept_candidate,
             "identity": validate_identity({key: model[key] for key in IDENTITY_KEYS})}
    register_entries(project, [entry], timestamp)
    return entry
